### ISSUE TITLE
نپذیرفتن سابدامنه

### ISSUE THREAD

**Issue by aliasqar** [GFW4Fun/x-ui-pro#12]
سلام
هر سابدامینی که میزنم دوباره Enter available subdomain (sub.domain.tld): نمایش داده می شود

**Comment by faridRezvani** [comment]
مشکل از عدم تنظیم بودن dns سرور هست.
لینک مقاله زیر را مطالعه کن:
https://github.com/hiddify/Hiddify-Manager/wiki/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%D8%AA%D9%86%D8%B8%DB%8C%D9%85-DNS-%D8%B3%D8%B1%D9%88%D8%B1#%D8%AA%D9%86%D8%B8%DB%8C%D9%85-dns-%D8%A7%D8%B2-%D8%B7%D8%B1%DB%8C%D9%82-ssh
