### ISSUE TITLE
Adding new domain

### ISSUE THREAD

**Issue by mehdiabr** [GFW4Fun/x-ui-pro#19]
hello  How can we add another additional domain so that we can use another company's CDN??

**Comment by GFW4Fun** [comment]
yes

**Comment by mehdiabr** [comment]
> yes

!!! How?

**Comment by GFW4Fun** [comment]
You can run several times
`sudo su -c "bash <(wget -qO- https://raw.githubusercontent.com/GFW4Fun/x-ui-pro/master/x-ui-pro.sh) -install yes -panel 0 -ONLY_CF_IP_ALLOW no"`
And multiple domains can be installed on a server

**Comment by Saleh-Mumtaz** [comment]
doesn't the add domain option work for this purpose?
