### ISSUE TITLE
403 Nginx Error After New Version Installation

### ISSUE THREAD

**Issue by seyedrezabazyar** [GFW4Fun/x-ui-pro#20]
In the new version, after installation, I encounter a 403 error from nginx. I tested this on two separate servers and with three different domains, but the issue persists.

**Comment by GFW4Fun** [comment]
send error text
`nginx -t`

**Comment by GFW4Fun** [comment]
Enter the Domain without ip character because  is not valid and not secure!
Example: **191.12.14.145_vps.hetzner.com**  not valid and not secure!

**Comment by seyedrezabazyar** [comment]
> send error text `nginx -t`

root@segaro:~# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

--------------------

I use a subdomain that is like this: sub.domain.com

--------------------

Error: 403 Forbidden \n nginx

**Comment by GFW4Fun** [comment]
```
wget https://raw.githubusercontent.com/GFW4Fun/x-ui-pro/master/x-ui-pro.sh
nano x-ui-pro.sh
```
#remove line 147-148-149-150

`bash ./x-ui-pro.sh  -install yes -panel 0 -ONLY_CF_IP_ALLOW no`
