### ISSUE TITLE
Cloud Flare Origin Certs instead of Let's Encrypt

### ISSUE THREAD

**Issue by Saleh-Mumtaz** [GFW4Fun/x-ui-pro#21]
Hi, thank you for your great script!
Can you help me to instead of using Let's Encrypt Certs, use CF's origin certificates? Because they are valid for 15 years, and with proxy on, the renewal process will be distorted.

**Comment by iopq** [comment]
it doesn't let me install at all without giving the subdomain and I don't want to use let's encrypt, I have my own certs
