### ISSUE TITLE
Get Real ip connections

### ISSUE THREAD

**Issue by intellvold** [GFW4Fun/x-ui-pro#23]
Hello, how can I get the user's real ip like getting the ip in the http protocol using X forward headers? Is there a way to do this without a domain? Or on a protocol that can be done in v2ray ?

**Comment by Saleh-Mumtaz** [comment]
In the inbound using cdn, enable acceptproxyprotocol, i saw the nginx config file, the x real ip for grpc and x forwarded for for websocket were in the config.

**Comment by Saleh-Mumtaz** [comment]
@GFW4Fun Hi, Is what i said correct?

**Comment by GFW4Fun** [comment]
Hi
your cdn is on?

```
proxy_set_header	X-Real-IP $remote_addr;
proxy_set_header	X-Forwarded-For $http_cf_connecting_ip;
proxy_set_header	CF-Connecting-IP $http_cf_connecting_ip;
```

**Comment by Saleh-Mumtaz** [comment]
Yes it is on, but i saw in the bash that you already placed these in nginx config.

**Comment by intellvold** [comment]
I installed according to the instructions. I entered the domain . and the script got a certificate for this domain, and I opened the panel link that the script gave me ,  in the browser and tried to create an inbound with the websocket protocol, but the user's real IP was still not visible in the xui logs . In CDN, everything is open

 and on the same domain, you can see the real IP in http get or post requests. but not show in xui logs when user connect vpn.

After installing the script and raising the panel in the browser using the domain. and creating ws inbound?

Do I have to do anything ?

> Hi your cdn is on?
> 
> ```
> proxy_set_header	X-Real-IP $remote_addr;
> proxy_set_header	X-Forwarded-For $http_cf_connecting_ip;
> proxy_set_header	CF-Connecting-IP $http_cf_connecting_ip;
> ```

**Comment by intellvold** [comment]
For some security and server connection issue, I want to know real IP of users when connecting to vpn using V2ray core.  In the xui logs, I can see IPs, but a bunch of ISPs, including my own. The router shows the central IP of the isp as the connection.  While the actual IP is visible when the send or receive request is sent from the client to the server. I wanted to know how the same x forwarded scenario can be fully implemented in v2ray without the need to edit the client anymore because these things can be manipulated on the client side. I would be grateful if you know a solution for not using the domain, or if you know how it works with the domain. Because in the documentation of this repository, I could not fully understand how it works

> Hi your cdn is on?
> 
> ```
> proxy_set_header	X-Real-IP $remote_addr;
> proxy_set_header	X-Forwarded-For $http_cf_connecting_ip;
> proxy_set_header	CF-Connecting-IP $http_cf_connecting_ip;
> ```

**Comment by intellvold** [comment]
> acceptproxyprotocol

After creating inbound and activating a series of things in nginx, what exactly should I do to see the IP logs? Should I use xui logs or is there another command for this? I am not able to see these items in the xui logs and also when I refer to the nginx logs it only shows http requests in the logs.

**Comment by GFW4Fun** [comment]
Run the installation again! 
The script was updated! to v2.3.5

**Comment by Saleh-Mumtaz** [comment]
@GFW4Fun 我使用了ChatGPT进行翻译，方便您的阅读。感谢您的出色工作。我想知道，NGINX是否支持TCP TLS xtls-rprx-vision？另外，在您看来，Caddy、NGINX和HAProxy哪个更好？

**Comment by GFW4Fun** [comment]
> @GFW4Fun 我使用了ChatGPT进行翻译，方便您的阅读。感谢您的出色工作。我想知道，NGINX是否支持TCP TLS xtls-rprx-vision？另外，在您看来，Caddy、NGINX和HAProxy哪个更好？

Maybe TCP support in the future!

**Comment by Saleh-Mumtaz** [comment]
@GFW4Fun 你的工作非常宝贵。非常感谢！期待看到你的项目进展。

**Comment by Saleh-Mumtaz** [comment]
@GFW4Fun 
我想和你们分享一些东西。在伊朗，"REALITY "因检测到 dest 和 sni 解析的 ip 与 vps 的 ip 无关而被阻止。因此，我们在这里进行了自我偷窃，虽然 "REALITY "的目的是使用流行网站的 tls 指纹，但我们使用的是托管在自己服务器上的真正 https 网站。Let's Encrypt 免费证书与现实百分之百兼容。来自 gfw 的攻击发生在服务器的 443 端口。
Nginx 会捕获从 443 端口进入的流量，而我不能使用 443 端口进行（REALITY）配置。因此，我想知道是否有可能让nginx不拦截（REALITY）流量，而是将其转发到xray，而不做任何更改或变形？

**Comment by Saleh-Mumtaz** [comment]
@GFW4Fun My good man, just tell me if it is possible or not.

**Comment by hazharKurdi** [comment]
remove this script cod plz
