### ISSUE TITLE
splithttp not working

### ISSUE THREAD

**Issue by mozaroc** [GFW4Fun/x-ui-pro#28]
Can you tell how to convigure vless via splitHTTP. I can't find the parameters, could you tell me what to do? There is a 404 error in the nginx log

 "POST /38985/asdfqwserf/e8124a77-70f5-4b2b-9571-ef357f775302/0?x_padding=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 HTTP/2.0" 404 0 "-" "Go-http-client/2.0"

**Comment by GFW4Fun** [comment]
Hi
i test with vless/ws and cloudflare cdn on
works But the protocol still has bug

**Comment by GFW4Fun** [comment]
Does not work with the new splithttp
