### ISSUE TITLE
why it doesn't work while cloudflare proxied is enable? 

### ISSUE THREAD

**Issue by KupQ** [GFW4Fun/x-ui-pro#40]
![image](https://github.com/user-attachments/assets/9c9c279a-552f-46cf-a39e-c778341e7864)

could you please take a look what am i doing wrong ?

**Comment by GFW4Fun** [comment]
Proxy Protocol = Off

-------------------------------

If you want to use CDN, you can turn off the proxy but enter the IP or Domain form cloudflare in config address
example:  www.speedtest.net:443 or 104.221.13.24:443


![image](https://github.com/user-attachments/assets/90ba3afb-663d-485a-9b7f-43d0c7d06ba3)

**Comment by KupQ** [comment]
> ## Proxy Protocol = Off
> External Proxy = [www.speedtest.net](http://www.speedtest.net) or any cloudflare site or cloudflare ip
> If you want to use CDN, you can turn off the proxy but enter the IP or Domain form cloudflare in config address example: [www.speedtest.net:443](http://www.speedtest.net:443) or 104.221.13.24:443
> 
> ![image](https://private-user-images.githubusercontent.com/146182012/393543347-90ba3afb-663d-485a-9b7f-43d0c7d06ba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NjU2MjIsIm5iZiI6MTczMzY2NTMyMiwicGF0aCI6Ii8xNDYxODIwMTIvMzkzNTQzMzQ3LTkwYmEzYWZiLTY2M2QtNDg1YS05YjdmLTQzZDBjN2QwNmJhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxMzQyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzcxNTA0M2U3NDExMzM5YzU1Y2Q0Yjg4NzNmYTYwYjNjOGVjYjhiODhlOTlkYjhlZDQ0OTBjNjUyODQ5MjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7GcCbixHzHAzroVBCk5Bq6mjsUMQm4Fayzh-MNoGwS4)

Thank you for the help, but i just tried it using cloudflare warp. the setup seems very easy and works perfectly fine.
