### ISSUE TITLE
enter available subdomain

### ISSUE THREAD

**Issue by mbehzad-bhz** [GFW4Fun/x-ui-pro#6]
وقتی ساب دامین را میزنم همش کامند را تکرار میکنه و اصلا نصب نمیشه

**Comment by Afarhud** [comment]
منم همین مشکلو دارم

**Comment by alireza-almoham** [comment]
منم همین مشکلو دارم

**Comment by EarlVadim** [comment]
For a long time I could not understand the cause of this problem, but it turned out that this is a problem with some VPS images.
you need to fix DNS on the server.
try installing **dnsutils**
and if it doesn’t help, fix the DNS server manually
nano /etc/resolv.conf  ->  1.1.1.1 or 8.8.8.8
