### ISSUE TITLE
Question: does x-ui-pro VLESS support Cloudflare DNS if the DNS is Proxied? Or does it only supports DNS-only?

### ISSUE THREAD

**Issue by arslyte** [GFW4Fun/x-ui-pro#9]
Using Cloudflare for DDNS; using A Records.

![image](https://github.com/GFW4Fun/x-ui-pro/assets/82070634/ef45c382-bbd9-4f2d-b472-9499030cad8e)

**Comment by EarlVadim** [comment]
Both options
